/**
 * Food Driver API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateOrderRequestMenuItemsInner } from './create-order-request-menu-items-inner';


export interface CreateOrderRequest { 
  [key: string]: any | any;


    /**
     * Unikalny identyfikator
     */
    idRestaurant: number;
    street: string;
    building: string;
    apartment: string;
    postalCode: string;
    city: string;
    menuItems: Array<CreateOrderRequestMenuItemsInner>;
    toPay: string;
}

