/**
 * Food Driver API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateOrderRequestMenuItemsInner { 
  [key: string]: any | any;


    /**
     * Unikalny identyfikator
     */
    idMenuItem: number;
    quantity: number;
}

