/**
 * Food Driver API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetOrder200ResponseClient } from './get-order200-response-client';


export interface GetOrder200ResponseDeliverer { 
    /**
     * Unikalny identyfikator
     */
    idUser: number;
    name: string;
    surname: string;
}

