/**
 * Food Driver API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ListMeOrders200ResponseResultsInnerRestaurantCategory } from './list-me-orders200-response-results-inner-restaurant-category';


export interface GetMeRestaurant200ResponseCategory { 
    /**
     * Unikalny identyfikator
     */
    idCategory: number;
    name: string;
}

