/**
 * Food Driver API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetOrder200ResponseOrderItemsInner { 
  [key: string]: any | any;


    /**
     * Unikalny identyfikator
     */
    idOrderItem: number;
    name: string;
    quantity: number;
    price: string;
    image: string;
}

