/**
 * Food Driver API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SignUpRequest { 
  [key: string]: any | any;


    name: string;
    surname: string;
    email: string;
    confirmEmail: string;
    password: string;
    confirmPassword: string;
}

