/**
 * Food Driver API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateMeRequest { 
  [key: string]: any | any;


    name: string;
    surname: string;
    street: string;
    building: string;
    apartment: string;
    postalCode: string;
    city: string;
}

