/**
 * Food Driver API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserRole } from './user-role';


export interface UpdateUserRequest { 
  [key: string]: any | any;


    role: UserRole;
    active: boolean;
}
export namespace UpdateUserRequest {
}


