/**
 * Food Driver API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type UserRole = 'Klient' | 'Restaurator' | 'Dostawca' | 'Administrator';

export const UserRole = {
    Klient: 'Klient' as UserRole,
    Restaurator: 'Restaurator' as UserRole,
    Dostawca: 'Dostawca' as UserRole,
    Administrator: 'Administrator' as UserRole
};

