export * from './categories.service';
import { CategoriesService } from './categories.service';
export * from './categories.serviceInterface';
export * from './deliveries.service';
import { DeliveriesService } from './deliveries.service';
export * from './deliveries.serviceInterface';
export * from './images.service';
import { ImagesService } from './images.service';
export * from './images.serviceInterface';
export * from './orders.service';
import { OrdersService } from './orders.service';
export * from './orders.serviceInterface';
export * from './restaurants.service';
import { RestaurantsService } from './restaurants.service';
export * from './restaurants.serviceInterface';
export * from './users.service';
import { UsersService } from './users.service';
export * from './users.serviceInterface';
export const APIS = [CategoriesService, DeliveriesService, ImagesService, OrdersService, RestaurantsService, UsersService];
