/**
 * Food Driver API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ListMeOrders200ResponseResultsInnerRestaurantCategory } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface CategoriesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * Przegląd kategorii
     */
    listCategories(extraHttpRequestParams?: any): Observable<Array<ListMeOrders200ResponseResultsInnerRestaurantCategory>>;

}
