/**
 * Food Driver API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ListMeOrders200Response } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface DeliveriesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * Przegląd dostępnych dostaw
     * @param lat Szerokość geograficzna
     * @param _long Długość geograficzna
     * @param distance Dystans (w metrach)
     * @param page Numer strony
     */
    listDeliveries(lat?: number, _long?: number, distance?: number, page?: number, extraHttpRequestParams?: any): Observable<ListMeOrders200Response>;

    /**
     * 
     * Przyjęcie dostawy do realizacji
     * @param id Unikalny identyfikator zamówienia
     */
    realizeDelivery(id: number, extraHttpRequestParams?: any): Observable<{}>;

}
