/**
 * Food Driver API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateImage201Response } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ImagesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * Utworzenie zdjęcia
     * @param image 
     */
    createImage(image: Blob, extraHttpRequestParams?: any): Observable<CreateImage201Response>;

}
