/**
 * Food Driver API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { GetRestaurant200Response } from '../model/models';
import { ListRestaurants200Response } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface RestaurantsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * Przegląd szczegółów restauracji
     * @param id Unikalny identyfikator restauracji
     */
    getRestaurant(id: number, extraHttpRequestParams?: any): Observable<GetRestaurant200Response>;

    /**
     * 
     * Przegląd restauracji
     * @param lat Szerokość geograficzna
     * @param _long Długość geograficzna
     * @param address Adres
     * @param distance Dystans (w metrach)
     * @param idCategory Unikalny identyfikator kategorii
     * @param page Numer strony
     */
    listRestaurants(lat?: number, _long?: number, address?: string, distance?: number, idCategory?: number, page?: number, extraHttpRequestParams?: any): Observable<ListRestaurants200Response>;

}
